# Site settings
title: UTSA Open Cloud Institute Training
title_short: UTSA OCI Training
description: > # this means to ignore newlines until "baseurl:"
  Tutorials, blog posts, and research papers on cloud computing.
  Topics include: security, networking, Docker, OpenStack, and Hadoop.
  Specific examples for NSF-funded Chameleon Cloud.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://cloudandbigdatalab.github.com" # the base hostname & protocol for your site
github_username:  cloudandbigdatalab

# Build settings
markdown: kramdown

permalink: pretty:
